config/routes.rb
Rails.application.routes.draw do

  root 'categories#index'

  resources :users, only: [:new, :show, :edit, :update, :create]
  resources :restaurants, only: [:new, :show, :edit, :update, :create] do
    resources :reservations, only: [:new, :show, :edit, :update, :create, :destroy]
    resources :reviews, only: [:show, :create, :edit, :update, :destroy]
  end
  resources :categories, only: [:index]
  get '/reservations' => 'reservations#index'
  get '/reviews' => 'reviews#index'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
  validates :party_size, :seating_time, presence: true
  validates :party_size, numericality: {only_integer: true, greater_than_or_equal_to: 2, less_than_or_equal_to: 20}
  validate :seating_time_cannot_be_in_the_past
  validate :capacity_exists


  def seating_time_cannot_be_in_the_past
  	if seating_time.present?
  		errors.add(:seating_time, "reservation can't be in the past") if seating_time < Date.today
      errors.add(:seating_time, "reservation should be on the hour") if seating_time.min != 0
      errors.add(:seating_time, "reservation should be between 11am and 8pm") if !(seating_time.hour).between?(11,20)
  	end
  end

  def available?
	 Reservation.where(seating_time: self.seating_time, restaurant_id: self.restaurant_id ).sum(:party_size) + party_size <= self.restaurant.capacity
  end

  def capacity_exists
  	unless available?
  		errors.add(:party_size, "would exceed capacity for this time slot")
  	end
  end


end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_action :authenticate_user
  before_action :get_restaurant, only: [:new, :show, :edit, :update, :destroy, :create]
  before_action :get_reservation, only: [:show, :edit, :update, :destroy]
  before_action :user_reservation_authorization, only: [:show, :edit, :update, :destroy]

  def index
    @reservations = Reservation.where(user_id: current_user)
  end

  def show
  end

  def new
    @reservation = @restaurant.reservations.build
  end

  def create
    @reservation = @restaurant.reservations.build(reservation_params)
    @reservation.user = current_user
    if @reservation.save
      redirect_to restaurant_path(@restaurant), notice: "Your reservation was successfully created!"
    else
      flash[:alert] = "Sorry, you can't make that reservation"
      render :new
    end
  end

  def edit
  end

  def update
    if @reservation.update_attributes(reservation_params)
      redirect_to restaurant_path(@restaurant), notice: "Successfully updated your reservation at #{@reservation.restaurant.name}."
    else
      render :edit
    end
  end

  def destroy
    if @reservation.destroy
      flash[:notice] = "Reservation has been cancelled"
      redirect_to reservations_path
    else
      render :edit
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:restaurant_id, :user_id, :seating_time, :party_size)
  end

  def get_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def get_reservation
    @reservation = @restaurant.reservations.find(params[:id])
  end

  def user_reservation_authorization
    get_reservation
    unless @reservation.user_id == current_user.id
      flash[:alert] = "Unauthorized to access this reservation"
      redirect_to root_path
    end
  end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<div class="form">
	<%= form_for ([@restaurant, @reservation]) do |f| %>
		<% if @reservation.errors.any? %>
			<div class="errors">
				<p>Reservation failed:</p>
				<ul>
					<% @reservation.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<div class="labels">
			<p><%= f.label :seating_time %></p>
			<p><%= f.label :party_size %></p>
		</div>
		<div class="inputs">
			<p><%= f.datetime_local_field :seating_time %></p>
			<p><%= f.number_field :party_size %></p>
		</div>
		<div class="submit">
			<p><%= f.submit  %></p>
		</div>
	<% end %>
</div>

app/views/reservations/edit.html.erb
<h1>Edit your reservation at <%= @reservation.restaurant.name %></h1>

<%= render 'form' %>

<%= link_to "Cancel my reservation", restaurant_reservation_path(@reservation.restaurant, @reservation), method: 'delete', data: { confirm: "Are you sure you want to cancel?" } %>

app/views/reservations/index.html.erb
<h1>All reservations for <%= current_user.first_name %></h1>

<% if @reservations.any? %>

		<% @reservations.each do |reservation| %>
			<p><%= reservation.restaurant.name %></p>
			<p><%= reservation.seating_time %></p>
			<p><%= reservation.party_size %></p>
			<p><%= link_to "Edit Reservation", edit_restaurant_reservation_path(reservation.restaurant, reservation) %></p>
		<% end %>

<% else %>
	<p>No Reservations for <%= current_user.first_name %></p>
<% end %>

app/views/reservations/new.html.erb
<h1>Create a new reservation at <%= @restaurant.name %></h1>

	<%= render 'form' %>

app/views/reservations/show.html.erb
<h1>Viewing your reservation at <%= @reservation.restaurant.name %></h1>

	<p><%= @reservation.seating_time %></p>
	<p><%= @reservation.party_size %></p>