config/routes.rb
Rails.application.routes.draw do

  root 'categories#index'

  resources :users, only: [:new, :show, :edit, :update, :create]
  resources :restaurants, only: [:new, :show, :edit, :update, :create] do
    resources :reservations, only: [:new, :show, :edit, :update, :create, :destroy]
    resources :reviews, only: [:show, :create, :edit, :update, :destroy]
  end
  resources :categories, only: [:index]
  get '/reservations' => 'reservations#index'
  get '/reviews' => 'reviews#index'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :owner, class_name: "User", foreign_key: "user_id"
  has_many :reservations
  has_many :reviews
  belongs_to :category
  validates :name, presence:true
  validates :name, uniqueness: { case_sensitive: false,  scope: [:street_number, :street_name, :city, :province, :country] }
  geocoded_by :full_address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  def is_owned_by?(user)
  	owner == user
  end

  def full_address
  		"#{street_number} #{street_name}, #{city}, #{province}, #{country}"
  		
  end

end

app/controllers/restaurant_controller.rb
class RestaurantController < ApplicationController


before_action :get_restaurant, only: [:show, :edit, :update]

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path, notice: "Successfully signed up for a Seat Yourself account."
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @restaurant.update_attributes(restaurant_params)
      redirect_to root_path, notice: "Successfully updated your restaurant account"
    else
      render :edit
    end
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :summary, :street_number, :street_name, :city, :province, :postal_code, :country, :phone_number, :website_url)
  end

  def get_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

before_action :authenticate_user, only: [:edit, :update]
before_action :get_restaurant, only: [:show, :edit, :update]
before_action :owner_authorized, only: [:edit, :update]


  def new
    unless current_user.owned_restaurant
      @restaurant = Restaurant.new
    else
      flash[:alert] = "You already own a restaurant! Cannot own more than one."
      redirect_to restaurant_path(current_user.owned_restaurant)
    end
  end

  def create
  	@user = current_user
    @restaurant = @user.create_owned_restaurant(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant), notice: "Successfully signed up for a Seat Yourself account."
    else
      render :new
    end
  end

  def show
    if current_user
      @review = @restaurant.reviews.build
      @hash = Gmaps4rails.build_markers(@restaurant) do |restaurant, marker|
        marker.lat restaurant.latitude
        marker.lng restaurant.longitude
      end
    end
  end

  def edit
  end

  def update
    if @restaurant.update_attributes(restaurant_params)
      redirect_to restaurant_path(@restaurant), notice: "Successfully updated your restaurant details"
    else
      render :edit
    end
  end


  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :summary, :street_number, :street_name, :city, :province, :postal_code, :country, :phone_number, :website_url)
  end

  def get_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def owner_authorized
    get_restaurant
    unless @restaurant.is_owned_by?(current_user)
      flash[:alert] = "You do not own this restaurant."
      redirect_to restaurant_path(@restaurant)
    end
  end
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/views/restaurants/_form.html.erb
<div class="form">
  <%= form_for(@restaurant) do |f| %>

  <% if @restaurant.errors.any? %>
      <div id="error">
        <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

        <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="labels">
      <p><%= f.label :name %></p>
      <p id="summary"><%= f.label :summary %></p>
      <p><%= f.label :street_number %></p>
      <p><%= f.label :street_name %></p>
      <p><%= f.label :city %></p>
      <p><%= f.label :province %></p>
      <p><%= f.label :postal_code %></p>
      <p><%= f.label :country %></p>
      <p><%= f.label :phone_number %></p>
      <p><%= f.label :website_url %></p>
    </div>

    <div class="inputs">
      <p><%= f.text_field :name %></p>
      <p><%= f.text_area :summary %></p>
      <p><%= f.number_field :street_number %></p>
  	  <p><%= f.text_field :street_name %></p>
      <p><%= f.text_field :city %></p>
      <p><%= f.text_field :province %></p>
      <p><%= f.text_field :postal_code %></p>
      <p><%= f.text_field :country %></p>
      <p><%= f.text_field :phone_number %></p>
      <p><%= f.text_field :website_url %></p>
    </div>

  	<div class="submit">
    	<%= f.submit %>
  	</div>
  <% end %>
</div>

app/views/restaurants/_restaurant_list.html.erb
<div class="restaurant-list">
	<% @restaurants.each do |restaurant| %>
		<div class="restaurant">
			<p><%= link_to "#{restaurant.name}", restaurant_path(restaurant) %></p>
			<p><%= restaurant.category.category_name %></p>
		</div>
	<% end %>
</div>

app/views/restaurants/edit.html.erb
<h1>Edit your Restaurant details</h1>

	<%= render 'form' %>
	<%= link_to 'Back', restaurants_path %>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant</h1>

	<%= render 'form' %>
	<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


<h1>Showing details for <%= @restaurant.name %></h1>

<%= link_to "Back to home", categories_url %> |
<%= link_to "Edit", edit_restaurant_path(@restaurant) %>

<p>Name: <%= @restaurant.name %> </p>
<p>Summary: <%= @restaurant.summary %></p>

<p>Address: <%= "#{@restaurant.street_number} #{@restaurant.street_name}" %> </p>
<p>City: <%= @restaurant.city %> </p>
<p>Province: <%= @restaurant.province %> </p>
<p>Country: <%= @restaurant.country %> </p>
<p>Postal Code: <%= @restaurant.postal_code %> </p>
<p>Capacity: <%= @restaurant.capacity %> </p>
<p>Phone: <%= @restaurant.phone_number %> </p>
<p>Website: <%= @restaurant.website_url %> </p>

<% if current_user != nil %>
	<% if @restaurant.is_owned_by?(current_user) %>
		<% current_user.owned_restaurant.reservations.each do |reservation| %>
			<p><%= "#{reservation.id}: #{reservation.user.first_name} #{reservation.user.last_name}, #{reservation.seating_time}, #{reservation.party_size}" %></p>
			<% end %>
	<% else %>
		<p><%= link_to "Make a reservation", new_restaurant_reservation_path(@restaurant) %></p>
	<% end %>
<% else %>
	<p>
		<%= link_to 'Login to make a reservation', login_path %>
	</p>
<% end %>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript"> 
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
	  	markers = handler.addMarkers
	    markers = handler.addMarkers(<%=raw @hash.to_json %>);
	  	handler.bounds.extendWith(markers);
	  	handler.fitMapToBounds();
		});
</script>

<h1>Reviews</h1>

<% if current_user && @restaurant.is_owned_by?(current_user) != true %>
	<p>Leave a new Review</p>
	<%= render partial: 'reviews/review_form' %>
	<p>All reviews</p>
	<%= render partial: 'reviews/review', collection: @restaurant.reviews.order(created_at: :desc) %>
<% elsif current_user && @restaurant.is_owned_by?(current_user) %>
	<p>All reviews for your restaurant</p>
	<%= render partial: 'reviews/review', collection: @restaurant.reviews.order(created_at: :desc) %>
<% else %>
	<p>
		<%= link_to 'Login to leave your own review', login_path %>
	</p>
	<%= render partial: 'reviews/review', collection: @restaurant.reviews.order(created_at: :desc) %>
<% end %>