config/routes.rb
Rails.application.routes.draw do

  root 'categories#index'

  resources :users, only: [:new, :show, :edit, :update, :create]
  resources :restaurants, only: [:new, :show, :edit, :update, :create] do
    resources :reservations, only: [:new, :show, :edit, :update, :create, :destroy]
    resources :reviews, only: [:show, :create, :edit, :update, :destroy]
  end
  resources :categories, only: [:index]
  get '/reservations' => 'reservations#index'
  get '/reviews' => 'reviews#index'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :get_restaurant, only: [:create, :edit, :update, :destroy]
  before_action :get_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:new, :create, :update, :edit, :destroy]

  def index
    @reviews = Review.where(user_id: current_user)
  end

  def show
  end

  def create
    @review = @restaurant.reviews.build(review_params)
    @review.user = current_user
    if @review.save
      redirect_to restaurant_path(@restaurant), notice: "Review has been added to #{@restaurant.name}"
    else
      render 'restaurants/show'
    end
  end

  def edit
    user_review_authorization
  end

  def update
    user_review_authorization
    if @review.update_attributes(review_params)
      redirect_to restaurant_path(@restaurant), notice: "Successfully updated review"
    else
      render :edit
    end
  end

  def destroy
    user_review_authorization
    if @review.destroy
      flash[:notice] = "Review has been deleted"
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  private

  def get_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def get_review
    @review = @restaurant.reviews.find(params[:id])
  end

  def user_review_authorization
    get_review
    unless @review.user_id == current_user.id
      flash[:alert] = "Unauthorized to edit this review"
      redirect_to root_path
    end
  end

  def review_params
    params.require(:review).permit(:title, :body, :restaurant_id, :user_id)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_review.html.erb
<div class="review">
	<p><%= review.title %></p>
	<p><%= review.body %></p>
	<% if review.user != nil %>
		<p>by <%= review.user.email %> </p>
		<p>Added on:
			<time><%= review.created_at %></time>
		</p>
	<% end %>
	<% if review.written_by?(current_user) %>
		<p>
			<%= link_to 'Edit review', edit_restaurant_review_path(review.restaurant_id, review.id) %> |
			<%= link_to 'Delete Review', restaurant_review_path(review.restaurant_id, review.id), method: 'delete', data: { confirm: "Are you sure you want to delete this review?" } %>
		</p>
	<% end %>
</div>

app/views/reviews/_review_form.html.erb
<div class="form">
<%= form_for ([@restaurant, @review]) do |f| %>
	<% if @review.errors.any? %>
		<div class="errors">
			<p>Review failed:</p>
			<ul>
				<% @review.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="labels">
		<p><%= f.label :title %></p>
		<p><%= f.label :body %></p>
	</div>
	<div class="inputs">
		<p><%= f.text_field :title %></p>
		<p><%= f.text_area :body %></p>
	</div>
	<div class="submit">
		<p><%= f.submit %></p>
	</div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit this review</h1>

<%= render 'review_form' %>

app/views/reviews/index.html.erb
<h1>Reviews written by <%= current_user.first_name %></h1>

<% @reviews.each do |review| %>
		<p>Ate at: <%= review.restaurant.name %></p>
		<p>Left review on: <%= review.created_at %></p>
		<p>Review title: <%= review.title %></p>
		<p>Review:</p>
		<p><%= review.body %></p>
<% end %>