config/routes.rb
Rails.application.routes.draw do

  root 'categories#index'

  resources :users, only: [:new, :show, :edit, :update, :create]
  resources :restaurants, only: [:new, :show, :edit, :update, :create] do
    resources :reservations, only: [:new, :show, :edit, :update, :create, :destroy]
    resources :reviews, only: [:show, :create, :edit, :update, :destroy]
  end
  resources :categories, only: [:index]
  get '/reservations' => 'reservations#index'
  get '/reviews' => 'reviews#index'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="logo" class="col-xs-3">
			<p>Seat Yourself</p>
		</div>
		<% if current_user %>
			<div class="navmenu" class="col-xs-9">
		    <p>Logged in as <%= current_user.email %>.</p>
				<p>
					<%= link_to "My Reservations", reservations_path %>
					<%= link_to "My Reviews", reviews_path %>
					<%= link_to "My Profile", user_path(current_user) %>
					<%= link_to "Log Out", session_path(current_user), method: 'delete' %>
				</p>
			</div>
		<% else %>
			<div class="navmenu" class="col-xs-9">
				<p>Welcome to Seat Yourself</p>
				<p>
					<%= link_to "Sign Up", signup_path %>
					<%= link_to "Log in", login_path %>
				</p>
			</div>
		<% end %>
	</div>
</div>
<div class="container">
	<div class="menu" class="col-xs-3">
		<br>
		<p>Home</p>
		<p>About Seat Yourself</p>
		<p>Restaurant Categories</p>
		<p>All Restaurants</p>
		<p>Placeholder</p>
		<p>Placeholder</p>
		<p>Placeholder</p>
	</div>
	<div class ="content" class="col-xs-9">
		<div id="flashes">
			<% if flash[:notice] %>
				<p><%= flash[:notice] %></p>
			<% elsif flash[:alert] %>
				<p><%= flash[:alert] %></p>
			<% end %>
		</div>
		<%= yield %>
	</div>
</div>
</body>
</html>